language: node_js
node_js: -'8'
sudo: false
jobs:
  include:
    - stage: Staging deploy
      name: Deploy to AWS staging
      env:
        - REACT_APP_DEPLOY_ENV=staging
      before_deploy:
        - npm run build
      deploy:
        provider: s3
        access_key_id: "$AWS_ACCESS_KEY_ID"
        secret_access_key: "$AWS_SECRET_ACCESS_KEY"
        on:
          branch: master
          condition: "$REACT_APP_DEPLOY_ENV = staging"
        bucket: "test-canary-deploy-travis"
        local_dir: build
        skip_cleanup: true
